TRANSLATIONS = {
    'en': {
        'manage_files': 'Manage Files',
        'new_folder_placeholder': 'New folder name',
        'create': 'Create',
        'existing_folders': 'Existing folders',
        'files': 'files',
        'folder_content': 'Folder content',
        'upload': 'Upload',
        'new_folder_name': 'New folder name',
        'rename': 'Rename',
        'cancel': 'Cancel',
        'delete_confirm': 'Do you really want to delete this file?',
        'delete_folder_confirm': 'Do you really want to delete this folder and all its contents?',
        'error': 'Error',
        'try_again': 'An error occurred, please try again later.',
        'file_deleted_success': 'File {filename} successfully deleted!',
        'file_delete_error': 'Error deleting file: {error}',
        'file_not_found': 'File not found.',
        'folder_deleted_success': 'Folder {folder} successfully deleted!',
        'folder_delete_error': 'Error deleting folder: {error}',
        'folder_not_found': 'Folder not found.',
        'folder_renamed_success': 'Folder successfully renamed from {old_folder} to {new_folder}',
        'folderNameEmpty': 'Le nom du dossier ne peut pas être vide'
    },
    'fr': {
        'manage_files': 'Gérer les fichiers',
        'new_folder_placeholder': 'Nom du nouveau dossier',
        'create': 'Créer',
        'existing_folders': 'Dossiers existants',
        'files': 'fichiers',
        'folder_content': 'Contenu du dossier',
        'upload': 'Uploader',
        'new_folder_name': 'Nouveau nom de dossier',
        'rename': 'Renommer',
        'cancel': 'Annuler',
        'delete_confirm': 'Voulez-vous vraiment supprimer ce fichier ?',
        'delete_folder_confirm': 'Voulez-vous vraiment supprimer ce dossier et tout son contenu ?',
        'error': 'Erreur',
        'try_again': 'Une erreur est survenue, veuillez réessayer plus tard.',
        'file_deleted_success': 'Fichier {filename} supprimé avec succès!',
        'file_delete_error': 'Erreur lors de la suppression du fichier : {error}',
        'file_not_found': 'Fichier non trouvé.',
        'folder_deleted_success': 'Dossier {folder} supprimé avec succès!',
        'folder_delete_error': 'Erreur lors de la suppression du dossier : {error}',
        'folder_not_found': 'Dossier non trouvé.',
        'folder_renamed_success': 'Dossier renommé avec succès de {old_folder} à {new_folder}',
        'folderNameEmpty': 'Folder name cannot be empty'
    }
}